server:
  service:
    type: ClusterIP

global:
  domain: argocd.skanth306.shop

configs:
  params:
    server.insecure: true

namespaceOverride: "argocd"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.skanth306.shop  # defaults to global.domain
    path: /
    pathType: Prefix

    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # extraTls:
    #   - hosts:
    #     - argocd.example.com
    #     # Based on the ingress controller used secret might be optional
    #     secretName: wildcard-tls