# without tls working fine
---
# global:
#   domain: argocd.skanth306.shop

# configs:
#   params:
#     server.insecure: true

# server:
#   ingress:
#     enabled: true
#     ingressClassName: nginx
#     # hostname: argocd.skanth306.shop
#     # path: /
#     # pathType: Prefix
#     annotations:
#       nginx.ingress.kubernetes.io/ssl-redirect: "false"
#       nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     # tls: false
#     extraPaths: []
#     extraRules:
#       - http:
#           paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: my-argo-cd-argocd-server
#                 port:
#                   number: 80   # 🚨 force HTTP port
---
# SSL-Passthrough
# global:
#   domain: argocd.skanth306.shop

# configs:
#   params:
#     server.insecure: false   #bydefault this is false--if true--> ArgoCD stays HTTP internally

# certificate:
#   enabled: true

# server:
#   ingress:
#     enabled: true
#     ingressClassName: nginx
#     # hostname: argocd.skanth306.shop
#     # path: /
#     # pathType: Prefix
#     annotations:
#       nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#       nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#     tls: true
---
# SSL Termination at Ingress Controller
global:
  domain: argocd.skanth306.shop

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true
    extraTls:
      - hosts:
        - argocd.skanth306.shop
        # Based on the ingress controller used secret might be optional
        secretName: my-wild-card-tls