server:
  service:
    type: ClusterIP

# global:
#   domain: argocd.example.com

configs:
  params:
    server.insecure: true

namespaceOverride: "argocd"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # extraTls:
    #   - hosts:
    #     - argocd.example.com
    #     # Based on the ingress controller used secret might be optional
    #     secretName: wildcard-tls