# without tls working fine
---
# global:
#   domain: argocd.skanth306.shop

# configs:
#   params:
#     server.insecure: true

# server:
#   ingress:
#     enabled: true
#     ingressClassName: nginx
#     # hostname: argocd.skanth306.shop
#     # path: /
#     # pathType: Prefix
#     annotations:
#       nginx.ingress.kubernetes.io/ssl-redirect: "false"
#       nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     # tls: false
#     extraPaths: []
#     extraRules:
#       - http:
#           paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: my-argo-cd-argocd-server
#                 port:
#                   number: 80   # 🚨 force HTTP port
---
global:
  domain: argocd.skanth306.shop

configs:
  params:
    server.insecure: false   #if true--> ArgoCD stays HTTP internally

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    # hostname: argocd.skanth306.shop
    # path: /
    # pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true

