{{- if .Values.nginxIngress.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.1
      helm:
        valueFiles:
          - nginx-values.yaml   # pulled from GitHub repo
          - $values/app-of-apps/chart-value-files/ingress-nginx/ingress-nginx.yaml   # pulled from GitHub repo
    - repoURL: https://github.com/srikanthhg/azure-bicep-files.git
      targetRevision: main
      ref: values                      # alias to reference values repo
  destination:
    server: {{ .Values.nginxIngress.destinationAKSServer }} # https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- else }}
apiVersion: v1
kind: List
items: []      
{{- end }}