apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reports
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: https://boldreports.github.io/bold-reports-kubernetes
      chart: boldreports
      targetRevision: 10.1.11 
      helm:
        values: |
          # Default values for boldreports.
          # This is a YAML-formatted file.
          # Declare variables to be passed into your templates.
          namespace: bold-services
          # appBaseUrl: 'reports.myzone.com'
          optionalLibs: 'postgresql' # mysql,oracle,postgresql,snowflake
          clusterProvider: 'aks'

          persistentVolume:
            # persistent volumes were global resources. 
            # so if you already have Bold Reports installed in your cluster, then the previous persistent volume name will conflict with current installation.
            # Change this name to avoid conflicts with previous Bold Reports persistent volumes.
            name: bold-fileserver
            capacity: 3Gi
            aks:
              fileShareName: 'forboldreports'
              # base64 string
              azureStorageAccountName: 'bXlzdG9hY2Nmb3Jib2xkCg=='
              # base64 string
              azureStorageAccountKey: 'VG1WOWRSbWplOVNuSEI3b29HcjFuZTVTbVRJN2pRTFVvMDZwdCtNWkxac3dqRTV4MHgvYWNyRmtCc2hsUUo0a1h1TUpPZ3R5WkVWWStBU3RZS3NxaWc9PQo='

              # To configure persistent volume using NFS fileshare, provide the following values:
              # Note: The premium storage account of the NFS fileshare must be within the same subscription as the AKS cluster.
              nfs:
                # fileshare name as 'storageaccountname/filesharename' Ex:premiumstorage1234/boldreports.
                fileShareName: 'forboldreports'

                # hostname of the fileshare Ex:premiumstorage1234.file.core.windows.net.
                hostName: 'mystoaccforbold.file.core.windows.net'

          image:
            idRepo: us-docker.pkg.dev/boldreports/v10-1-11
            reportsRepo: us-docker.pkg.dev/boldreports/v10-1-11
            # Overrides the image tag whose default is the chart appVersion.
            idTag: 10.1.11
            reportsTag: 10.1.11
            pullPolicy: IfNotPresent
          imagePullSecrets: []

          loadBalancer:
            type: nginx
            affinityCookie:
              enable: true
              affinityCookieExpiration: 600
            # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
            # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
            ingressClassName: nginx

            nginxIngressAnnotations:
              # Enter annotations here for adding annotations in nginx ingress
              # Example:
              # cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/rewrite-target: /

            # singleHost: 
            #   secretName: bold-tls
            # multipleHost:
              # hostArray:
                # - hosts: 
                    # - kubernetes.docker.internal
                    # - example.com
                  # secretName: bold-tls
          autoscaling:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: bold-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true