controller:
  replicaCount: 2
  admissionWebhooks:
    enabled: false
  service:
    type: LoadBalancer
    # enabled: true
    # external:
    #   enabled: false
    # internal:
    #   enabled: true
    #   annotations:
    #     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #   loadBalancerIP: ""
